#! /bin/bash

DOCKER_HOME=/home/arsenal
ARSENAL_DIR=$(dirname $(readlink -f $0))

usage() {
    echo Usage: ./$(basename $0) \[source\] \[destination\]
}

if [[ $1 == -h || $1 == --help ]]; then
  usage
  exit 0
fi

if [[ $# -eq 0 ]]; then
    vol=$ARSENAL_DIR/shared:$DOCKER_HOME/shared
elif [[ $# -eq 1 ]]; then
    vol=$1:$DOCKER_HOME/$(basename $1)
elif [[ $# -eq 2 ]]; then
    vol=$1:$DOCKER_HOME/$2
else
    usage
    exit 1
fi

## GUI Support (https://stackoverflow.com/a/25280523)
XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth
touch $XAUTH
xauth nlist :0 | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -

## BURP Dir
burp_dir=$ARSENAL_DIR/_data/.java/.userPrefs/burp:$DOCKER_HOME/.java/.userPrefs/burp
burp_conf=$ARSENAL_DIR/_data/.BurpSuite:$DOCKER_HOME/.BurpSuite

## -u flag = https://github.com/moby/moby/issues/3206#issuecomment-152682860
docker run -it --rm -h arsenal --name arsenal \
    -u $(id -u):$(id -g) \
    -v $XSOCK:$XSOCK -v $XAUTH:$XAUTH -e XAUTHORITY=$XAUTH \
    -v $vol \
    -v $burp_dir -v $burp_conf \
    -p 8080:8080 \
    --env="DISPLAY" \
    --cap-add=SYS_PTRACE --security-opt seccomp=unconfined \
    arsenal 

